### ISSUE TITLE
[HELP] Add checks (required by libevent)

### ISSUE THREAD

**Issue by helmesjo** [build2/libbuild2-autoconf#1]
I'm packaging [`libevent`](https://github.com/build2-packaging/libevent) (see here), and it requires a quite extensive list of defines (for specifying available symbols, headers etc while building), and any help to implement these would be appreciated. :)

Attached file contains a (filtered) list of all the defines used somewhere in the source of `libevent`.
See [here](https://github.com/build2/libbuild2-autoconf/tree/master/libbuild2-autoconf#adding-new-checks) for instructions on how to add new checks. Just double-check it [isn't already implemented](https://github.com/build2/libbuild2-autoconf/tree/master/libbuild2-autoconf/libbuild2/autoconf/checks).

**If you do one or more**, please just list them in a comment here to avoid duplicate work.

Thanks in advance!

[LIBEVENT-defines-used.txt](https://github.com/build2/libbuild2-autoconf/files/9444574/LIBEVENT-defines-used.txt)

**Comment by helmesjo** [comment]
- HAVE_ARC4RANDOM
- HAVE_ARC4RANDOM_BUF
- HAVE_ARC4RANDOM_ADDRANDOM
- HAVE_ARPA_INET_H
- HAVE_CLOCK_GETTIME
- HAVE_GETRANDOM
- HAVE_DEVPOLL
- HAVE_NETDB_H
- HAVE_FD_MASK
- HAVE_EPOLL

**Comment by boris-kolpackov** [comment]
Maybe the first step should be to filter out those that are already implemented and then group the rest into related functionality (like `HAVE_ARC4*`, `HAVE_ARPA_*` and other inet-related ones, etc).

**Comment by EmilRosenquist** [comment]
@boris-kolpackov @helmesjo I added a PR #2 for getnameinfo, Is this the change that is required?

**Comment by boris-kolpackov** [comment]
@EmilRosenquist Yes, looks good.

**Comment by boris-kolpackov** [comment]
> but either way you'll notice straight away when `HAVE_XXX.h` already exists

Ok, I guess check if the test is already implemented before picking it from the list.

**Comment by EmilRosenquist** [comment]
Ill start going through these

- [ ] HAVE_GETADDRINFO
- [ ] HAVE_GETEGID
- [ ] HAVE_GETEUID
- [ ] HAVE_GETHOSTBYNAME_R
- [ ] HAVE_GETHOSTBYNAME_R_3_ARG
- [ ] HAVE_GETHOSTBYNAME_R_5_ARG
- [ ] HAVE_GETHOSTBYNAME_R_6_ARG
- [ ] HAVE_GETIFADDRS
- [ ] HAVE_GETNAMEINFO
- [ ] HAVE_GETPROTOBYNUMBER
- [ ] HAVE_GETSERVBYNAME
- [ ] HAVE_GETTIMEOFDAY

**Comment by helmesjo** [comment]
**Remaining defines to do:**
[defines-remaining.txt](https://github.com/build2/libbuild2-autoconf/files/9454292/defines-remaining.txt)

**Comment by EmilRosenquist** [comment]
All the ones assigned to me are now in PR, waiting for review/merge.
