### ISSUE TITLE
SIZEOF_PTHREAD_T is broken on Linux, FreeBSD, MinGW

### ISSUE THREAD

**Issue by boris-kolpackov** [build2/libbuild2-autoconf#47]
I looked at the current implementation of `SIZEOF_PTHREAD_T` and was pretty sure it's broken:

```
#ifndef _WIN32
#   if defined(__APPLE__)
#       ifdef __LP64__
#           define SIZEOF_PTHREAD_T 8
#       else
#           define SIZEOF_PTHREAD_T 4
#       endif
#   else
#       define SIZEOF_PTHREAD_T 4
#   endif
#
```

Specifically, this `else` branch looks outright bogus:

```
#ifndef _WIN32
...
#   else
#       define SIZEOF_PTHREAD_T 4
#   endif
#

```

So I've added a runtime test for it and sure enough `sizeof(pthread_t)` is not 4 on 64-bit Linux or FreeBSD. Also, there is `pthread` on MinGW. Here is the CI: https://ci.stage.build2.org/@eadf8618-7d94-48d9-be62-32067d3cbb4b

If think this needs to be re-implemented properly on the libc by libc basis (i.e., on glibc it's that, on FreeBSD it's this, on Apple its something else, etc).

@EmilRosenquist @helmesjo

**Comment by EmilRosenquist** [comment]
@boris-kolpackov Please review #48

**Comment by boris-kolpackov** [comment]
Merged, thanks!
