### ISSUE TITLE
[HELP] Add checks (required by thrift)

### ISSUE THREAD

**Issue by helmesjo** [build2/libbuild2-autoconf#49]
I'm currently packaging [`thrift`](https://github.com/apache/thrift) and after filtering out unused defines I concluded the following list of missing checks:

*  ~~AI_ADDRCONFIG~~
*  ~~STRERROR_R_CHAR_P~~
*  ~~HAVE_SIGNAL_H~~
*  ~~HAVE_POLL_H~~
*  ~~HAVE_SYS_POLL_H~~
*  ~~HAVE_SCHED_H~~
*  ~~HAVE_STRINGS_H~~
*  ~~HAVE_STRERROR_R~~
*  ~~HAVE_AF_UNIX_H~~
   * ~~**NOTE:** This exists as `HAVE_AFUNIX_H`, but @boris-kolpackov is looking into how to deal with these situations.~~
   * [FIXED](https://github.com/build2/libbuild2-autoconf/commit/367c4529d23a050017da93cad03711cdd07734ab)

See [here](https://github.com/apache/thrift/blob/2a93df80f27739ccabb5b885cb12a8dc7595ecdf/build/cmake/config.h.in) for description of each define.

**Comment by boris-kolpackov** [comment]
Anything left in this issue or can it be closed?

**Comment by helmesjo** [comment]
I would assume it's all done yes.
